### ISSUE TITLE
Erro na média

### ISSUE THREAD

**Issue by Kisrym** [Bebel132/outro-CRUDkk#1]
Quando você escolhe a opção de editar as notas, a nova média criada a partir das novas notas vem errada

(acontece pq tu converteu o input pra **int** em vez de **float** no App.editarNota)

**Comment by Bebel132** [comment]
![image](https://user-images.githubusercontent.com/48385634/189520227-cebbf528-8cc1-4c2f-9918-33d02de11f6d.png)

era isso?

**Comment by Kisrym** [comment]
isso memo
